### ISSUE TITLE
Wrong "if" closure of $ELEMENT_VOLUME_MULTIPLYER

### ISSUE THREAD

**Issue by lurpi** [ufz/ogs5#110]
Hi all,
The if block for reading $ELEMENT_VOLUME_MULTIPLYER starting at line https://github.com/ufz/ogs5/blob/master/FEM/rf_mmp_new.cpp#L1885 seems wrongly closed. Now it is like this: 

> 			          << "- times the grid value \n";
> 		}

Should it be like this? 

> 			          << "- times the grid value \n";
> 			in.clear();
> 			continue;
> 		}

Thanks for looking into the issue. Have a nice day

**Comment by wenqing** [comment]
Yes it should like this
------------------------

    |<< "- times the grid value \n"; in.clear(); continue; |

|It has to be corrected. Fortunately, the reading is at the end of the loop.|
||

**Comment by norihiro-w** [comment]
@lurpi  thanks for the report. The code is fixed now,
