### ISSUE TITLE
Reload with openmpi not working

### ISSUE THREAD

**Issue by waltherm** [ufz/ogs5#3]
Due to this change
https://github.com/wenqing/ogs5-trunk/commit/9c6fb5040200ec6f7abe27f67367d6d540043187
reloading a written solution (option $RELOAD 3 1) is not working anymore with mpi.

The change is part of this PR
https://github.com/envinf/ogs5-trunk/pull/134

I do not know, why the change was necessary.

@wenqing, can you please take a look here?

**Comment by wenqing** [comment]
@waltherm  The changes in ReadSolution and WriteSolution are just coding style changes. Should you or me create a PR for this issue?

**Comment by waltherm** [comment]
Well... Maybe, the problem we talked about was introduced even before this commit...?

**Comment by waltherm** [comment]
@wenqing why did you close the issue? Was it solved?
