### ISSUE TITLE
Crash with latest openmpi after recent merges

### ISSUE THREAD

**Issue by waltherm** [ufz/ogs5#34]
I need to use the latest openmpi (1.10.2) to fix a memory leak of the former versions. Unfortunately, I am now getting an error that seems to be related to the latest changes of @norihiro-w concerning mpi stuff. The error does not occur, when I go back to https://github.com/ufz/ogs5/commit/e0f23674dfb084382fe9ef8155ff41321231ed4d

I enclosed the error log, that is given, when I run the master with mpi 1.10.2.

@norihiro-w could you please take a look?

[err.log.txt](https://github.com/ufz/ogs5/files/182371/err.log.txt)

**Comment by norihiro-w** [comment]
I'll take a look...

**Comment by norihiro-w** [comment]
Does ogs fail in Jenkins benchmark as well? If it's specific to your problems, can you send me your input files? I can test it tomorrow.

**Comment by waltherm** [comment]
you'll need to compile openmpi 1.10.2 to test it

small test input can be found here:
/data/envinf/waltherm/TEST/goswami_TS-1-2_complete_constrain2_mpi

Jenkins shows some errors (also) for mpi benchmarks. didn't look into details...
