### ISSUE TITLE
Failed benchmarks

### ISSUE THREAD

**Issue by wenqing** [ufz/ogs5#37]
- [ ]  ~~BG-ECLIPSE_DUMUX/kinetic_CO2phase_generation_E100/CO2phase_gen_E100~~
- [ ]  ~~BG-ECLIPSE_DUMUX/kinetic_CO2phase_generation_E300/CO2phase_gen_E300~~
- [ ]  ~~BG-ECLIPSE_DUMUX/1phase_radialflow_1phase_transport/1pf_1pt~~
- [ ]  ~~BG-ECLIPSE_DUMUX/2phase_flow_2phase_tracertransport/2pf_2pt~~
- [x]  BG-C/2d_Cl_transport_Clay/Nuklidtransport
- [ ] ~~MW-DENSITY-DEPENDENT_FLOW/goswami-clement/constrBC_PressAsHead_tri/HM~~
- [ ] ~~MW-DENSITY-DEPENDENT_FLOW/goswami-clement/wholeBC_PressAsHead_tri/HM~~
- [x] CL-TES/heat_of_reaction/reaction_heat
- [x] TN-T2HC/heat_transfer/heat_transfer
- [x] TN-T2HC/heat_of_reaction/reaction_heat
- [x] TN-T2HC/friction/Friction_test
- [x] TN-T2HC/Convection_2D/conv_2D_cart
- [x] TN-T2HC/Convection_2D_axi/conv_2D_axi
- [x] HS-C/calcite_gems/calcite (GEMS)
- [x] HS-C/calcite_pqc/pds (PQC)
- [x] HS-C/comedy2d/cement2d (GEMS)
- [x]  CB-C/NAPL-dissolution/1D_NAPL-diss_flow/lin/1D_TPF_resS_flow
- [x] CB-C/Engesgaard/Kin/slow_kin_pqc/pds (PQC)
- [ ] ~~CB-C/Engesgaard/Kin/slow_kin_pqc_krc/pds (PQC)~~
- [x] FC-C/monod/rt1 (BRNS)
- [x] NB-FLUID_PROPERTIES/H2T_McWhorter_PwSnw/h2t_line (MKL)
- [x] HS-PETSC/ConcreteCrack/decal (PETSC_GEMS)
- [x]  HS-PETSc/TransLay2d/lag2d  (PETSC_GEMS)

**Comment by norihiro-w** [comment]
@wenqing There are some more CB-C benchmarks failing (https://svn.ufz.de:8443/job/OGS-5/job/ufz/branch/master/12/) after merging your PR. Can you have a look at them?

**Comment by wenqing** [comment]
@norihiro-w Ok.

**Comment by norihiro-w** [comment]
The followings can be fixed by updating the reference files
- HS-C/calcite_gems/calcite (GEMS)
- HS-C/calcite_pqc/pds (PQC)

**Comment by norihiro-w** [comment]
For  CB-C/Engesgaard/Kin/slow_kin_pqc/pds (PQC) and CB-C/Engesgaard/Kin/slow_kin_pqc_krc/pds (PQC), the benchmark script and config type should be corrected. These two should be tested with FEM config, not PQC config, since it needs to call Phreeqc executable. PQC config uses internal Phreeqc lib.

**Comment by norihiro-w** [comment]
@wenqing can you also check PETSC/ConcreteCrack/decal (PETSC_GEMS)?

**Comment by wenqing** [comment]
@norihiro-w  As far as I could remember,  Geog asked to disable PETSC/ConcreteCrack/decal.
Some running errors are
```
 Unknown porosity model!
 Unknown diffusion model!
```

**Comment by norihiro-w** [comment]
@wenqing please check out the latest master. PETSC_GEMS config didn't work in previous versions.

**Comment by wenqing** [comment]
@norihiro-w  It works, but the compilation needs boost being installed in advance. Just updated the result.

**Comment by norihiro-w** [comment]
@wenqing I don't think we can simply update the reference result for ConcreteCrack. As I wrote yesterday, there is a huge difference in hydraulic head.

**Comment by wenqing** [comment]
@norihiro-w  Sorry I just checked the distribution of the concentration of comportments but the element velocity. Just checked the output of the element velocity of liquid/groundwater flow process, and it works good.

I  have to reset the repository now.

**Comment by norihiro-w** [comment]
ConcreteCrack benchmark is now fixed. There was a problem in a GEMS input file.

**Comment by wenqing** [comment]
:+1:

**Comment by norihiro-w** [comment]
all T2HC and TES benchmarks are fixed.

**Comment by waltherm** [comment]
The goswami-clement benchmarks are both fine in setup and reference. @norihiro-w can you please activate them again?
