### ISSUE TITLE
OGS5 Benchmarking on Jenkins: There might be a bug in cmake script

### ISSUE THREAD

**Issue by wenqing** [ufz/ogs5#48]
@bilke @norihiro-w 

On Jenkins, a command of " nice -n 5 make benchmarks-short-normal-long" is executed to run all benchmarks. The thing is that some benchmarks are commonly below to benchmarks-short, benchmarks--normal, and benchmarks-long, while the benchmarking is run by multi-thread processors.  Under such situation, some benchmarks are run by more than one threads simultaneously, which leads a mess output data like the way of data racing during writing.

I have tested to run the benchmarks with commands  make benchmarks-short, make benchmarks-normal, make benchmarks-long, individually. This gives failed benchmarks as expected. On the contrary,  the command  "nice -5 make benchmarks-short-normal-long" leads more unreasonable failures in the benchmarking.

@bilke Could you please take a look at this?

**Comment by norihiro-w** [comment]
@wenqing I couldn't reproduce the problem. Which benchmarks run multiple time?

**Comment by wenqing** [comment]
@norihiro-w  I forgot which, and I am testing again.

**Comment by wenqing** [comment]
@norihiro-w Strange. my current test dose not show the data race. Both tests that by ctest and nice -4 make benchmarks-short-normal-long give the same results, and the failed benchmarks are
```
         19 - BG-ECLIPSE_DUMUX/1phase_radialflow_1phase_transport/1pf_1pt (Failed)
         20 - BG-ECLIPSE_DUMUX/2phase_flow_2phase_tracertransport/2pf_2pt (Failed)
         21 - BG-ECLIPSE_DUMUX/2phase_flow_radialmodel/2pf_radialmodel (Failed)
         22 - BG-ECLIPSE_DUMUX/kinetic_CO2phase_generation_E100/CO2phase_gen_E100 (Failed)
         23 - BG-ECLIPSE_DUMUX/kinetic_CO2phase_generation_E300/CO2phase_gen_E300 (Failed)
         24 - BG-C/2d_Cl_transport_Clay/Nuklidtransport (Failed)
         53 - CL-TES/heat_of_reaction/reaction_heat (Failed)
         76 - MW-DENSITY-DEPENDENT_FLOW/goswami-clement/constrBC_PressAsHead_tri/HM (Failed)
         77 - MW-DENSITY-DEPENDENT_FLOW/goswami-clement/wholeBC_PressAsHead_tri/HM (Failed)
        123 - TN-T2HC/heat_transfer/heat_transfer (Failed)
        124 - TN-T2HC/heat_of_reaction/reaction_heat (Failed)
        125 - TN-T2HC/friction/Friction_test (Failed)
        126 - TN-T2HC/Convection_2D/conv_2D_cart (Failed)
        127 - TN-T2HC/Convection_2D_axi/conv_2D_axi (Failed)
```

Therefore, I close this issue.
