### ISSUE TITLE
v.5.7.1 does not compile on win64 using VisualStudio 2015

### ISSUE THREAD

**Issue by norihiro-w** [ufz/ogs5#75]
Report from Luca Urpi,

> On a side note, at least to me, 5.7.1 does not compile on win64 (using
> VisualStudio 2015) , giving the following error:
> 
> Error:C2280
> 'Eigen::Block<Derived,1,-1,false,true>
> &Eigen::Block<Derived,1,-1,false,true>::operator =(const
> Eigen::Block<Derived,1,-1,false,true> &)': attempting to reference a
> deleted functionObject: FEM
> File: thirdparty\eigen\src\QR\FullPivHouseholderQR.h
> line: 506
> 
> while 5.7.0 compiles (it uses a different version of the above mentioned
> FullPivHouseholderQR.h file).

**Comment by bilke** [comment]
Is fixed with https://github.com/ufz/ogs5/commit/273ebbe5d77f5de7247cf55e7adddfb18cd638de.
